name: Debug Pull-Request

on:
  pull_request_target:
    # (re)opened PR or new commit in fork
    types: [ opened, synchronize, reopened ]

jobs:
  debug:
    name: Debug Pull-Request
    # NOTE: on windows as computing of descriptors has a bug on linux right now
    runs-on: windows-2019
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} # needed for pulling R packages from github

    steps:
      - name: SSH
        uses: mxschmitt/action-tmate@v3
